services:
  - type: web
    name: starbucks-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: starbucks-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://starbuck-cups-frontend.vercel.app
      - key: SOCKET_CORS_ORIGIN
        value: https://starbuck-cups-frontend.vercel.app

databases:
  - name: starbucks-db
    databaseName: starbucks_shop
    user: starbucks_user
    plan: free